run_name: "graphAttn_flow_matching"
epochs: 400
batch_size: 64
num_workers: 4
pin_memory: true
persistent_workers: true
prefetch_factor: 2

message_passing_mode: "attention" # mlp, attention
resume: true
resume_ckpt: "checkpoints/wgwnxpac/graphAttn_flow_matching_last.pt"

lr: 1.0e-4
early_stop_patience: 200

# model
hidden_dim: 128
num_layers: 9
norm: true
type_loss_scale: 4.0
bond_loss_scale: 8.0
charge_loss_scale: 1000.0
count_loss_scale: 0.5
max_ligand_atoms: 64
steps: 100
