run_name: "graphAttn_flow_matching"
epochs: 300
batch_size: 64
num_workers: 4
pin_memory: true
persistent_workers: true
prefetch_factor: 2

message_passing_mode: "attention" # mlp, attention
resume: false
# resume_ckpt: "checkpoints/7nogxr5q/paper_reproduction_last.pt"

early_stop_patience: 200

# model
hidden_dim: 128
num_layers: 9
norm: true
type_loss_scale: 1.0
steps: 100